pipelines:
  validateEmail:
    - step: validateEmail.checkSyntax
      cost: 1
    - step: validateEmail.checkDomainMX
      cost: 5
    - step: validateEmail.checkDisposable
      cost: 3
    - step: validateEmail.checkSpamList
      cost: 10
